apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-sensors
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-sensors
spec:
  source:
    git:
      url: https://github.com/VikyaSurve/spring-sensors
      ref:
        branch: main
